import { IsEmail, IsOptional, IsString, MaxLength, MinLength } from 'class-validator';

export class DeviceIdentityDto {
  // Generated by the client and persisted per installation; never hardware-derived.
  @IsOptional()
  @IsString()
  @MaxLength(255)
  installationId?: string;

  @IsOptional()
  @IsString()
  @MaxLength(120)
  deviceName?: string;

  @IsOptional()
  @IsString()
  @MaxLength(40)
  platform?: string;
}

export class RegisterDto extends DeviceIdentityDto {
  @IsEmail()
  email!: string;

  @IsString()
  @MinLength(8)
  password!: string;

  @IsString()
  @MinLength(1)
  fullName!: string;

  @IsOptional()
  @IsString()
  phone?: string;
}

export class LoginDto extends DeviceIdentityDto {
  @IsEmail()
  email!: string;

  @IsString()
  password!: string;
}

export class RefreshDto {
  @IsString()
  refreshToken!: string;
}

export class ApproveDeviceDto {
  @IsString()
  @MinLength(32)
  approvalToken!: string;
}
